### ISSUE TITLE
Clarification needed on recent PR for `macro_names` parameter

### ISSUE THREAD

**Issue by carlca** [bram209/leptosfmt#114]
I would really like to use your `leptosfmt` to reformat `yew` files containing `html!` macros. I tried it out with a `leptosfmt.toml` file containing...

```toml
max_width = 100
tab_spaces = 2
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
macro_names = ["yew::html, html"]       # Macro names which will be formatted
```
but the source doesn't seem to change. This is the source I am trying to reformat...
```rust
use yew::prelude::*;

#[function_component]
fn App() -> Html {
  let counter = use_state(|| 0);
  let onclick = {
    let counter = counter.clone();
    move |_| {
      let value = *counter + 1;
      counter.set(value);
    }
  };

  html! {
      <div>
          <button {onclick}>{ "+1" }</button>
          <p>{ *counter }</p>
      </div>
  }
}

fn main() {
  yew::Renderer::<App>::new().render();
}
```

Any ideas?
