### ISSUE TITLE
Can we have macro names to exclude?

### ISSUE THREAD

**Issue by ekanna** [bram209/leptosfmt#117]
Hi,
I have a style! macro inside view! macro to generate scoped css.
How to skip formatting this style! macro?
Can we do something like ```macro_names_to_skip = [style]```

For example, from the below code style! macro generates a css file with @scope rule.

``` rust
#[component]
pub fn HeaderField() -> impl IntoView {
    view! {
        <div class="HeaderField start">
            <h1>Hello Kanna</h1>
        </div>

        {
            style! {
                h1 {
                    background-color: red;
                    color: white;
                }

                @media (orientation: portrait) {
                    h1 {
                      background-color: green;
                    }
                  }

            }
        }
    }
}
```

My generated css file

```css
@scope (.HeaderField) to (.start) {
    h1 {
        background-color: red;
        color: white;
    }

    @media (orientation: portrait) {
        h1 {
          background-color: green;
        }
      }

}
```
