### ISSUE TITLE
[Feature Request] AlwaysUnlessLit should include idents

### ISSUE THREAD

**Issue by BrandonDyer64** [bram209/leptosfmt#139]
It makes sense to have an option that doesn't put braces around numbers and strings, but It's a bit weird to see it then put braces around simple variable names.

**Current:**
```rust
<Component
    closure={move || 5} // Braces
    math={5 + 5}        // Braces
    number=5            // No Braces
    variable={some_var} // Braces?
/>
```

**Desired:**
```rust
<Component
    closure={move || 5} // Braces
    math={5 + 5}        // Braces
    number=5            // No Braces
    variable=some_var   // No Braces
/>
```

**Comment by bram209** [comment]
When I have a `leptosfmt.toml` with:
```toml
attr_value_brace_style = "AlwaysUnlessLit"
```

And run:
```bash
echo "fn test() { view! { <Component closure={move || 5} math={5 + 5} number={5} variable={some_var} /> } }" | leptosfmt --stdin --rustfmt --max-width=60
```

The output is:

```rust
fn test() {
    view! {
        <Component
            closure={move || 5}
            math={5 + 5}
            number=5
            variable={some_var}
        />
    }
}
```

I am closing this issue, but feel free to reopen if you can't get it to work.

**Comment by BrandonDyer64** [comment]
@bram209 Yes I am. In fact, your output shows the problem.

```rust
fn test() {
    view! {
        <Component
            closure={move || 5}
            math={5 + 5}
            number=5
            variable={some_var} // <- This has curly braces, but there should be a config option that makes this not happen
        />
    }
}
```

**Comment by BrandonDyer64** [comment]
@bram209 I'm not able to reopen this

**Comment by bram209** [comment]
Ah my bad, when I glanced over this issue I didn't see that you actually want to not have curly braces when you pass a plain identifier. However, `AlwaysUnlessLit` will always put braces unless it's a _literal_ value, a variable value is not literal.

I could be open to adding a `Custom` variant, where you could specify with more granularity which expressions are to be formatted with braces and which without, like so:

```toml
attr_value_brace_style = "Custom"
attr_value_braces_exclude = [ "Array", "Range", "Literal",  "Ident" ] // with other options like "If", "Binary" (your `5 + 5` example), "Path"...
```

But one thing that I would like to avoid, is having leptos code being formatted in many different ways. I would love if leptos, as a community, could come to terms with a sane default to format things. What are your thoughts on this?

**Comment by BrandonDyer64** [comment]
> But one thing that I would like to avoid, is having leptos code being formatted in many different ways. I would love if leptos, as a community, could come to terms with a sane default to format things.

I absolutely agree with this sentiment, which is why I had originally requested it be added to `AlwaysUnlessLit`. In my opinion, if there is going to be an option that mixes braces and non-braces then it is sane to include idents with that.

I personally prefer it without braces in general, but still want to keep braces for expressions and closures.

**Comment by bram209** [comment]
> I _personally_ prefer it without braces in general, but still want to keep braces for expressions and closures.

I _personally_ prefer it with braces in general, but still want to omit braces for literal values. So my mixed feelings are:
- I have a different preference
- a variable identifier is not a literal value, unlike the name "AlwaysUnlessLit" suggests

What if I deprecate `attr_value_brace_style` in favor for:

```toml
default_attr_value_brace_style = "WhenRequired" # "WhenRequired", "Preserve", "Always"

# One or multiple `attr_value_brace_style` blocks, where you override styles for specific kind of expressions
[[attr_value_brace_style]] 
style = "Always" 
for = ["Block", "Closure"]
```

Would that work for you?
