### ISSUE TITLE
Combine `rustfmt` and `leptosfmt` using pipe operator

### ISSUE THREAD

**Issue by dandedotdev** [bram209/leptosfmt#164]
Hi, thanks for making leptosfmt!

I'm a developer who recently started using Leptos. I found that when using the recommended configuration from the README:

```toml
[rustfmt]
overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"]
```

Despite encountering some issues, such as automatic comment removal, the automatic formatting still provides a quite nice developer experience.

However, I noticed some parts that should have been handled by `rustfmt` weren't working correctly.

After some trying, I found this configuration that solves my needs:

```toml
[rustfmt]
overrideCommand = ["sh", "-c", "rustfmt --emit stdout | leptosfmt --stdin --rustfmt"]
```

I appreciate leptosfmt and have found it incredibly useful, but I'm also thinking adding this configuration to the README might better help developers like me who are new to the Leptos world.

I'm happy to create a PR for this and follow up with any required changes.
