### ISSUE TITLE
Leptosfmt removes spaces from macro text

### ISSUE THREAD

**Issue by Altaks** [bram209/leptosfmt#175]
Hi,
Let's say, i have the following code in a RSX `view!` macro : 

```html
<li>
  <span class="ms-3">"lorem ipsum" some text here</span>
</li>
```

When using leptosfmt on said file, it removes the spaces within the `some text here` part.

After triggering many reformats of the file, i end up with the following : 

```html
<li>
  <span class="ms-3">"lorem ipsum"sometexthere</span>
</li>
```

Similar behavior happens everywhere else in the file where there is non-double-quoted tokens in the view macro, like `<p>"Some text" this text will not be formatted normally</p>`

## Configuration

I have my VSC setup to format on save using the following configuration :

```json
"rust-analyzer.rustfmt.overrideCommand": [
  "leptosfmt",
  "--stdin",
  "--config-file",
  "${workspaceFolder}/leptosfmt.toml",
  "--rustfmt"
]
```

and here's the leptosfmt config : 

```toml
max_width = 170
tab_spaces = 2
newline_style = "Unix"
indentation_style = "Spaces"

# Macro names which will be formatted
macro_names = ["leptos::view", "view"]

[attr_values]
class = "Tailwind" # "Tailwind" is the only attribute value formatter available for now
```

The issue doesn't seem to come from a bad configuration, and I didn't find anything related in the documentation :/
